### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by tbalz2319**
Adding the cli command a user can use to install pip on their respective system

### CODE REVIEW

**Comment by tbalz2319** [comment]
anything else needed for this commit to go through?

**Comment by apsdehal** [comment]
I am still debating if we should add installation instructions here. We usually point to zardus/ctf-tools for the same.

**Comment by tbalz2319** [comment]
oh ok i see

**Comment by apsdehal** [comment]
We have decided not to include install commands and point to ctf-tools instead. Thanks for opening  up the PR. Looking for more contributions in future. :)

**Pull request merged**
